name: gcsl
channels:
- kne  # for pybox2d
- pytorch
- anaconda  # for mkl
dependencies:
  - flask=0.12.2=py35_0
  - joblib=0.9.4
  - mako=1.0.6=py35_0
  - matplotlib=2.0.2=np111py35_0
  - mkl=2018.0.2  # Need to add explicit dependence for pytorch
  - numba=0.35.0=np111py35_0
  - numpy=1.11.3
  - path.py=10.3.1=py35_0
  - pybox2d=2.3.1post2=py35_0
  - python=3.5.2
  - python-dateutil=2.6.1=py35_0
  - pytorch-cpu=1.1.0
  - torchvision-cpu
  - scipy=1.0.1
  - patchelf
  - scikit-learn
  - mpi4py
  - pip:
    - wheel
    - cloudpickle==0.5.2
    - cached-property==1.3.1
    - plotly==1.9.6
    - gym[all]==0.10.5
    - gitpython==2.1.7
    - gtimer==1.0.0b5
    - pygame==1.9.2
    - tqdm
    # For doodad:
    - awscli==1.11.179
    - boto3==1.4.8
    # I use these, but very rarely
    - dominate==2.3.1
    - ray==0.2.2
    # More optional ones:
    - catkin_pkg==0.3.9
    - ipdb==0.10.3
    - rospkg==1.1.4
    # mujoco-py<2.1,>=2.0
    - mujoco-py<1.50.2,>=1.50.1
    - scikit-video
    - opencv-python
    - box2d-py
